# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: V's homepage
description: Online portfolio
baseurl: ""
url: https://v-glb.github.io

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Welcome to my portfolio
  description:
    - Hello!
    - My name is Vadim
    - I'm a Full Stack Developer
    - Find out what I'm familiar with below
  # cv: assets/cv.pdf
  # address:
  #   - University of Jekyll
  #   - Department of Themes
  #   - 123 Main St, Anytown, USA
  cms:
    - Adobe Experience Manager
    - Magnolia
    - Drupal
    - Liferay
  languages:
    - HTML
    - CSS
    - LESS
    - JavaScript
    - PHP
    - MySQL
    - Java
    - Python
    - Bash
  frameworks:
    - React
    - Electron
    - Twig
    - Apache Sling
    - Spring Boot
  tools:
    - Docker
    - Git
    - CI/CD
    - REST
    - agile
    - markdown
  contact:
    email: v.glb@posteo.de
  source: https://github.com/v-glb/v-glb.github.io
  profiles:
    linkedin: https://www.linkedin.com/in/vadim-glebow-180471279/
    xing: 'https://www.xing.com/profile/Vadim_Glebow/cv'
    github: https://github.com/v-glb

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never
